const data = [
  {
    id: "RT3080",
    date: "19 Aug 2021",
    customer: "Jensen Huang",
    client: {
      name: "Jensen Huang",
      email: "jensenhuang@mail.com",
      address: "84 Church Way",
      city: "Bradford",
      postCode: "BD19PB",
      country: "United Kindom",
    },
    paymentTerms: "Net 30 Days",
    items: [
      {
        name: "Banner Design",
        qty: 1,
        price: 156.0,
      },
      {
        name: "Email Design",
        qty: 2,
        price: 200.0,
      },
    ],
    description: "Graphic Design",
    totalAmount: 1800.9,
    status: "paid",
  },
  {
    id: "XM9141",
    date: "20 Sep 2021",
    customer: "Alex Grim",
    client: {
      name: "Alex Grim",
      email: "alexgrim@mail.com",
      address: "84 Church Way",
      city: "Bradford",
      postCode: "BD19PB",
      country: "United Kindom",
    },
    paymentTerms: "Net 30 Days",
    items: [
      {
        name: "Banner Design",
        qty: 1,
        price: 156.0,
      },
      {
        name: "Email Design",
        qty: 2,
        price: 200.0,
      },
    ],
    description: "Graphic Design",
    totalAmount: 556,
    status: "pending",
  },
  {
    id: "RG0314",
    date: "01 Oct 2021",
    customer: "Jhon Morrison",
    client: {
      name: "Jhon Morrison",
      email: "jhonmorrison@mail.com",
      address: "84 Church Way",
      city: "Bradford",
      postCode: "BD19PB",
      country: "United Kindom",
    },
    paymentTerms: "Net 30 Days",
    items: [
      {
        name: "Banner Design",
        qty: 1,
        price: 156.0,
      },
      {
        name: "Email Design",
        qty: 2,
        price: 200.0,
      },
    ],
    description: "Graphic Design",
    totalAmount: 14002.33,
    status: "paid",
  },
  {
    id: "RT2080",
    date: "12 Oct 2021",
    customer: "Alysa Werner",
    client: {
      name: "Alysa Werner",
      email: "alysawerner@mail.com",
      address: "84 Church Way",
      city: "Bradford",
      postCode: "BD19PB",
      country: "United Kindom",
    },
    paymentTerms: "Net 30 Days",
    items: [
      {
        name: "Banner Design",
        qty: 1,
        price: 156.0,
      },
      {
        name: "Email Design",
        qty: 2,
        price: 200.0,
      },
    ],
    description: "Graphic Design",
    totalAmount: 102.04,
    status: "pending",
  },
  {
    id: "aa1449",
    date: "14 Oct 2021",
    customer: "Mellisa Clarke",
    client: {
      name: "Mellisa Clarke",
      email: "mellisaclarke@mail.com",
      address: "84 Church Way",
      city: "Bradford",
      postCode: "BD19PB",
      country: "United Kindom",
    },
    paymentTerms: "Net 30 Days",
    items: [
      {
        name: "Banner Design",
        qty: 1,
        price: 156.0,
      },
      {
        name: "Email Design",
        qty: 2,
        price: 200.0,
      },
    ],
    description: "Graphic Design",
    totalAmount: 4032.33,
    status: "pending",
  },
  {
    id: "Y91411",
    date: "31 Oct 2021",
    customer: "Thomas Wayne",
    client: {
      name: "Thomas Wayne",
      email: "thomaswayne@mail.com",
      address: "84 Church Way",
      city: "Bradford",
      postCode: "BD19PB",
      country: "United Kindom",
    },
    paymentTerms: "Net 30 Days",
    items: [
      {
        name: "Banner Design",
        qty: 1,
        price: 156.0,
      },
      {
        name: "Email Design",
        qty: 2,
        price: 200.0,
      },
    ],
    description: "Graphic Design",
    totalAmount: 6155.91,
    status: "pending",
  },
  {
    id: "FV2353",
    date: "12 Nov 2021",
    customer: "Anita Wainwright",
    client: {
      name: "Anita Wainwright",
      email: "anitawainwright@mail.com",
      address: "84 Church Way",
      city: "Bradford",
      postCode: "BD19PB",
      country: "United Kindom",
    },
    paymentTerms: "Net 30 Days",
    items: [
      {
        name: "Banner Design",
        qty: 1,
        price: 156.0,
      },
      {
        name: "Email Design",
        qty: 2,
        price: 200.0,
      },
    ],
    description: "Graphic Design",
    totalAmount: 3102.04,
    status: "draft",
  },
];

export default data;
